database:
  jdbcUrl: 'jdbc:mariadb://localhost:3307/pandorascluster?useSSL=false'
  username: 'root'
  password: '%Schueler90'
  driver: 'org.mariadb.jdbc.Driver'
  dialect: 'org.hibernate.dialect.MariaDBDialect'
