zombie-velocity-multiplier: 0.4
database:
  jdbcUrl: 'jdbc:mariadb://localhost:3306/pandorascluster?useSSL=false'
  username: 'pandorascluster'
  password: 'CoTayoC4wIbu'
  driver: 'org.mariadb.jdbc.Driver'
  dialect: 'org.hibernate.dialect.MariaDBDialect'