zombie-velocity-multiplier: 0.4

trusted-particle: REDSTONE
untrusted-particle: FLAME
particle-data:
  radius: 64
  speed: 1
  offX: 0
  offY: 0
  offZ: 0
  trusted-particle-data:
    red: 85
    green: 255
    blue: 85
    size: 2.5
    material: AIR
  untrusted-particle-data:
    red: 170
    green: 0
    blue: 0
    size: 2.5
    material: AIR


tasks:
  show-border-multiplier: 1
database:
  jdbcUrl: 'jdbc:mariadb://localhost:3306/pandorascluster?useSSL=false'
  username: 'pandorascluster'
  password: 'CoTayoC4wIbu'
  driver: 'org.mariadb.jdbc.Driver'
  dialect: 'org.hibernate.dialect.MariaDBDialect'